### ISSUE TITLE
How stable is this library?

### ISSUE THREAD

**Issue by DenuxPlays** [ranger-ross/actix-web-validation#13]
Hey,

I am thinking about implementing this library into my backend.
We currently use the actix-web-validator library.

I wondered if this library is ready to be used in a relatively stable backend?

**Comment by ranger-ross** [comment]
Hey there,

Thanks for the interest in this crate. I think I am pretty happy with the `Validated<T>` interface and don't see that changing in the near future. 

The error handling could probably be improved a bit, but I think `validator` is [planning to rework error handling](https://github.com/Keats/validator/issues/338) so I am thinking waiting for that before making any changes to this crates interface.

I also probably need to improve the CI for things like MSRV. 

If you are okay with the things above, I think this library is in a stable enough state to use. Until `validator` and `garde` hit a 1.0 release, I will probably keep this crate `0.x`.

**Comment by DenuxPlays** [comment]
That shound good.

I will implement the library today or tomorrow.
